### ISSUE TITLE
show shortlink only, when link was successfully created

### ISSUE THREAD

**Issue by lisah298** [JH-WebWorks/TinyGu#7]

**Comment by keiwanjamaly** [comment]
Display of short link is wrong. The short link is exactly the same thing, you are typing inside optional keyword (see Line 75 and 66). It should be the one returned by the backend.

https://github.com/JH-WebWorks/TinyGu/blob/9723ec5bdb311cdc806fc9a11be1864f04c80aaf/frontend/src/Main.tsx#L71-L78

https://github.com/JH-WebWorks/TinyGu/blob/9723ec5bdb311cdc806fc9a11be1864f04c80aaf/frontend/src/Main.tsx#L62-L68

**Comment by Bomel** [comment]
not solved
